#!/bin/sh -ex

DB_NAME=bambooinvoice
DB_USER=bambooinvoice
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/bambooinvoice

# unpack and fix permissions
unzip $SRC/bambooinvoice_*.zip -d $(dirname $WEBROOT)
rm $SRC/bambooinvoice_*.zip
find $WEBROOT -type f -print0 | xargs -0 chmod 644
find $WEBROOT -type d -print0 | xargs -0 chmod 755
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/img/logo
chown -R www-data:www-data $WEBROOT/invoices_temp
chown -R www-data:www-data $WEBROOT/bamboo_system_files/application/config

# tweak settings
CONF=$WEBROOT/bamboo_system_files/application/config/config.php
sed -i "s|^\$config\['base_url.*|\$config['base_url'] = '/';|" $CONF
sed -i "s|encryption_key.*|encryption_key'] = '$(mcookie)';|" $CONF
sed -i "s|index_page.*|index_page'] = '';|" $CONF
sed -i "s|sess_use_database.*|sess_use_database'] = TRUE;|" $CONF

CONF=$WEBROOT/bamboo_system_files/application/config/database.php
sed -i "s|username'\] =.*|username'] = '$DB_USER';|" $CONF
sed -i "s|password'\] =.*|password'] = '$DB_PASS';|" $CONF
sed -i "s|database'\] =.*|database'] = '$DB_NAME';|" $CONF
sed -i "s|dbprefix'\] =.*|dbprefix'] = '';|" $CONF
sed -i "s|db_debug'\] =.*|db_debug'] = FALSE;|" $CONF

mv $WEBROOT/possible.htaccess $WEBROOT/.htaccess

# configure apache
a2dissite default
a2ensite bambooinvoice
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/install"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL $URL --data "login_username=$EMAIL&primary_contact=Admin+User&login_password=$ADMIN_PASS&login_password_confirm=$ADMIN_PASS&login_credentials=Install"
$CURL ${URL}/update_bamboo

rm -f /tmp/cookie
rm $WEBROOT/bamboo_system_files/application/controllers/install.php

# set default domain
CONF=$WEBROOT/bamboo_system_files/application/config/config.php
sed -i "s|^\$config\['base_url.*|\$config['base_url'] = 'http://$DOMAIN/';|" $CONF

# tweak default configuration
$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE settings SET display_branding=\"n\", new_version_autocheck=\"n\", save_invoices=\"y\" WHERE id=1;"

# secure sensitive files
chmod 640 $WEBROOT/bamboo_system_files/application/config/config.php
chmod 640 $WEBROOT/bamboo_system_files/application/config/database.php

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

