#!/bin/sh -ex

DB_NAME=bambooinvoice
DB_USER=bambooinvoice
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/bambooinvoice

