#!/bin/bash -e
# regenerate bambooinvoice secrets and mysql password

. /etc/default/inithooks

ENCKEY=$(mcookie)
PASSWORD=$(mcookie)

CONF=/var/www/bambooinvoice/bamboo_system_files/application/config/config.php
sed -i "s|encryption_key.*|encryption_key'] = '$ENCKEY';|" $CONF

CONF=/var/www/bambooinvoice/bamboo_system_files/application/config/database.php
sed -i "s|password'\] =.*|password'] = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=bambooinvoice --pass="$PASSWORD"

